/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iutoj_user;

import com.sun.prism.paint.Color;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.ActionListener;
import static java.lang.Boolean.TRUE;

/**
 *
 * @author KAWSAR
 */
public class ProblemShow extends javax.swing.JFrame {

    UserDashboard parent;
    public ProblemShow(String time, String memory) {
        initComponents();
        timeLabel.setText(time);
        memoryLabel.setText(memory);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightPanel = new javax.swing.JPanel();
        memoryLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();
        ProblemNameLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        TLLabel = new javax.swing.JLabel();
        MemoryLimitLabel = new javax.swing.JLabel();
        TimeLimitLabel = new javax.swing.JLabel();
        MLLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memoryLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        memoryLabel.setForeground(new java.awt.Color(0, 181, 204));
        RightPanel.add(memoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, 30));

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(0, 181, 204));
        closeLabel.setText("x");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, 20));

        minimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(0, 181, 204));
        minimizeLabel.setText("_");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -20, 30, 40));

        SubmitButton.setBackground(new java.awt.Color(0, 181, 204));
        SubmitButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(0, 181, 204));
        SubmitButton.setText("Submit");
        SubmitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 150, 40));
        RightPanel.add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 280, -1));

        ProblemNameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        ProblemNameLabel.setForeground(new java.awt.Color(0, 181, 204));
        ProblemNameLabel.setText("Problem Name");
        RightPanel.add(ProblemNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 180, 30));

        timeLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 181, 204));
        RightPanel.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, 30));

        TLLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        TLLabel.setForeground(new java.awt.Color(0, 181, 204));
        TLLabel.setText("TL");
        RightPanel.add(TLLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 140, 30));

        MemoryLimitLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        MemoryLimitLabel.setForeground(new java.awt.Color(0, 181, 204));
        MemoryLimitLabel.setText("Memory Limit:");
        RightPanel.add(MemoryLimitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 30));

        TimeLimitLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        TimeLimitLabel.setForeground(new java.awt.Color(0, 181, 204));
        TimeLimitLabel.setText("Time Limit:");
        RightPanel.add(TimeLimitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 140, 30));

        MLLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        MLLabel1.setForeground(new java.awt.Color(0, 181, 204));
        MLLabel1.setText("ML");
        RightPanel.add(MLLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 140, 30));

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 560));

        setSize(new java.awt.Dimension(635, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_SubmitButtonButtonActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);      // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLabelMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MLLabel1;
    private javax.swing.JLabel MemoryLimitLabel;
    private javax.swing.JLabel ProblemNameLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TLLabel;
    private javax.swing.JLabel TimeLimitLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel memoryLabel;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
