/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iutoj_admin;

import java.io.File;
import javax.swing.JFrame;
import javax.swing.JPanel;
import newproblem.NewProblem;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
/**
 *
 * @author KAWSAR
 */
public class ProblemShow extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ProblemShow() {
        initComponents();
        this.setVisible(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        ProblemNameLabel = new javax.swing.JLabel();
        TimeLimitLabel = new javax.swing.JLabel();
        MemoryLimitLabel = new javax.swing.JLabel();
        viewerScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(0, 181, 204));
        closeLabel.setText("x");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, 20));

        minimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(0, 181, 204));
        minimizeLabel.setText("_");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -20, 30, 40));

        SubmitButton.setBackground(new java.awt.Color(0, 181, 204));
        SubmitButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(0, 181, 204));
        SubmitButton.setText("Submit");
        SubmitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 518, 150, 30));

        ProblemNameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        ProblemNameLabel.setForeground(new java.awt.Color(0, 181, 204));
        ProblemNameLabel.setText("Problem Name");
        RightPanel.add(ProblemNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 180, 30));

        TimeLimitLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        TimeLimitLabel.setForeground(new java.awt.Color(0, 181, 204));
        TimeLimitLabel.setText("Time Limit:");
        RightPanel.add(TimeLimitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 30));

        MemoryLimitLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        MemoryLimitLabel.setForeground(new java.awt.Color(0, 181, 204));
        MemoryLimitLabel.setText("Memory Limit:");
        RightPanel.add(MemoryLimitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, 30));
        RightPanel.add(viewerScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 620, 420));

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 560));

        setSize(new java.awt.Dimension(635, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void viewPdf(File problem){
        SwingController controller = new SwingController();
        controller.setToolBarVisible(false);
        SwingViewBuilder factory = new SwingViewBuilder(controller);
        JPanel viwerpanel = factory.buildViewerPanel();
        viewerScrollPane.setViewportView(viwerpanel);
        controller.openDocument(problem.getAbsolutePath());
    }
    private void SubmitButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonButtonActionPerformed

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);      // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MemoryLimitLabel;
    private javax.swing.JLabel ProblemNameLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TimeLimitLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JScrollPane viewerScrollPane;
    // End of variables declaration//GEN-END:variables
}
